### PR TITLE
RoR Capstone Project Culture and Science Blog

### PR DESCRIPTION
**Pull request by vicmaburrito**
## Science & Culture Blog 
The Design of this project is based on: https://www.notion.so/Lifestyle-articles-b82a5f10122b4cec924cd5d4a6cf7561
### Current gem's 
- Use Rubocop & Stylelint linters
- Use Bootstrap for Design
- Use Font-awesome
- Use Bulma Framework for Design of Navbar
### Setup 
-Create controller's & models of functions 
-Add model, views & controllers for a user session, Log in, Sign up & Log out 
-Add model, views & controllers for articles with CRUD 
-Add model & controllers votes for articles with all logic
### Description
The idea of this project is to test the different logic's and user interaction with the creation and deletion of users, articles, and votes, this project has been tested with **Rspec** using gems like Faker and Factory Bot for a better utility

### CODE REVIEW

**Comment by mke2111** [comment]
Screenshot from 2021-07-27 03-03-02

**Comment by vicmaburrito** [comment]
Hello, did you run the command db: seed?

**Comment by mke2111** [comment]
Yes, I did follow the steps in the readme file.

**Comment by vicmaburrito** [comment]
I ran the application in another folder locally and it works, I cannot find the error because it does not generate it in my local environment, a feedback would be helpful to me to fix it, tks for your time!

**Pull request merged**
